            echo "ğŸ“‚ Folder android sudah ada, lewati langkah ini."
          fi

      - name: ğŸ”„ Sinkronisasi Aset Web
        run: |
          echo "ğŸ”— Menyinkronkan aset web ke proyek Android..."
          npx cap sync android

      - name: ğŸ—ï¸ Build APK Debug
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: ğŸ“¤ Upload Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: ğŸ“± Eksperimen-LCG-By-Endang
          path: android/app/build/outputs/apk/debug/app-debug.apk
